# Executive Email Generation Project

## Objective
Clean a raw dataset of executives, identify senior leadership, and generate two likely corporate email addresses for 50 executives.

Steps:
- Load dirty CSV
- Filter senior executives
- Remove non-executive roles
- Strip duplicate records
- Rank by seniority
- Select top 50
- Add domains
- Generate email formats
- Export final list

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

## 2. Load Raw Dataset

In [2]:
df=pd.read_csv("cmo_videos_names.csv",on_bad_lines="skip")
df.head()

,Name,Title,Company,Youtube URL
0,Donna Johnson,Chief Marketing Officer,Inseego,https://www.youtube.com/watch?v=mwlCTdYh0uM
1,Andreas Urschitz,CMO,Infineon,https://www.youtube.com/watch?v=QUgwtmPtN8A
2,Robert Occhialini,Chief Technology Officer,World Surf League,https://www.youtube.com/watch?v=VkMVaML9yBc
3,Gabriel Romero,Chief Marketing Officer,AllCloud,https://www.youtube.com/watch?v=VkMVaML9yBc
4,Julie Neumann,Chief Marketing Officer,Honeycomb.io,https://www.youtube.com/watch?v=mIMHw1U2BPg

## 3. Filter Senior Executives and remove non execcutive roles

In [3]:
senior_titles=["CEO","Founder","Co-Founder","President",
    "COO","CFO","CTO","CMO","CIO",
    "Vice President","VP","SVP","EVP",
    ]
non_exec_titles=["Engineer","Developer","Analyst","Associate","Intern","Student","Assistant","Coordinator","Specialist","Consultant","Sales Rep",
               "Sales Representative","Marketing Executive","HR Executive","Recruiter","Talent","Support","Administrator","Admin",
               "Executive Assistant","Operations Associate","Director","Manager","Sr.","Senior Manager","GM","General Manager",
    "Managing Director",]
execs=df[df["Title"].str.contains("|".join(senior_titles), case=False, na=False)]
execs = execs[~execs["Title"].str.contains("not stated|unknown|n/a", case=False, na=False)]
execs = execs[~execs["Title"].str.contains("|".join(non_exec_titles), case=False)]
execs[["Name","Title"]]

                     Name                               Title
1        Andreas Urschitz                                 CMO
14        Michael Nicosia                    Co-Founder & COO
19          Mick Hollison                       Founder & CEO
20      Bernd Greifeneder  Chief Technology Officer & Founder
28   Danielle Goode Coady                     VP of Marketing
..                    ...                                 ...
337        Randy Arseneau                                 CMO
341          Marie Hattar                                 CMO
344             Steve Pao                                 CMO
352         Randy Arsenau                                 CMO
353       Steve Kenniston             VP of Product Marketing

[173 rows x 2 columns]

## 4. Remove Duplicate Records

In [15]:
execs = execs.drop_duplicates(subset=["Name","Company"])

## 5. Remove Evangelist / Field Roles

In [16]:
execs = execs[~execs["Title"].str.contains("evangelist", case=False, na=False)] #because sometimes they are not budget owners
execs = execs[~execs["Title"].str.contains("field", case=False, na=False)]      #they usually report to CTO who are the actual executive

## 6. Rank Executives by Seniority

In [17]:
def rank(title):
    t = title.lower()

    if "ceo" in t or "founder" in t or "president" in t:
        return 3

    if any(x in t for x in ["cmo","cto","cfo","coo","cio","chief marketing","chief technology","chief financial","chief operating","chief information"]):
        return 2

    if any(x in t for x in ["evp","svp","vp","gvp"]):
        return 1

    return 0
execs["rank"] = execs["Title"].apply(rank)
execs = execs.sort_values(by=["rank", "Name"], ascending=[False, True])
execs.head(20)

,Name,Title,Company,Youtube URL,rank
51,Abhay Parasnis,Founder & CEO,Typeface,https://www.youtube.com/watch?v=U1jdmFW7-f4,3
333,Ben Parr,Co-Founder & CMO,Octane AI,https://www.youtube.com/watch?v=riKER3eQixs,3
20,Bernd Greifeneder,Chief Technology Officer & Founder,Dynatrace,https://www.youtube.com/watch?v=6bBI-WZYvTo,3
132,Bill Largent,CEO,Veeam,https://www.youtube.com/watch?v=OdrhPIBgZoE,3
215,Boris Renski,Co Founder and CMO,Mirantis,https://www.youtube.com/watch?v=EcxoQizrOPw,3
152,Brandon Nott,Senior Vice President of Product,UiPath,https://www.youtube.com/watch?v=SJFpjG_J6W0,3
83,Brett Hannath,Corporate Vice President & CMO,Intel,https://www.youtube.com/watch?v=sAPATcXqel0,3
178,Calline Sanchez,Vice President,IBM Worldwide Systems Lab Services,https://www.youtube.com/watch?v=DEHUqmEwFeg,3
131,Carol Carpenter,Senior Vice President and Chief Marketing Officer,VMware,https://www.youtube.com/watch?v=5KcRXgaimYU,3
314,Jaspreet Singh,CEO,Druva,https://www.youtube.com/watch?v=cf1vPcFW5to,3
210,Jean English,Senior Vice President and Chief Marketing Officer,NetApp,https://www.youtube.com/watch?v=ualozF4rCog,3
227,John Bara,CMO & President,Mintigo,https://www.youtube.com/watch?v=bTSFqIFJqrs,3
157,Karin Toubba,CEO,Kenna Security,https://www.youtube.com/watch?v=8NBAkJMA0sM,3
14,Michael Nicosia,Co-Founder & COO,Salt Security,https://www.youtube.com/watch?v=g3LhSzFiz1c,3
19,Mick Hollison,Founder & CEO,Redline Advisors,https://www.youtube.com/watch?v=uHlrQWbdP7A,3
200,Partha Seetala,Co-founder and CTO,Robin.io,https://www.youtube.com/watch?v=s7VaHEspI7E,3
175,Samantha Choi Cadley,CEO,Manual Labor Studio,https://www.youtube.com/watch?v=Q0_2N5hcBKo,3
38,Sarbjeet Johal,Founder & CEO,Stackpane,https://www.youtube.com/watch?v=zF9IycsTdsA,3
170,Scott Hebner,Vice President & CMO,IBM Data & AI,https://www.youtube.com/watch?v=AQw62zAq7Lw,3
37,Shlomo Kramer,Co-Founder & CEO,Cato Networks,https://www.youtube.com/watch?v=3_Y-QFr_U7k,3

In [18]:
top50 = execs.head(50)
top50 = top50.reset_index(drop=True)
top50.index=top50.index+1
top50["Name"] = top50["Name"].str.replace(r'[^\w\s]', '', regex=True)
top50

,Name,Title,Company,Youtube URL,rank
1,Abhay Parasnis,Founder & CEO,Typeface,https://www.youtube.com/watch?v=U1jdmFW7-f4,3
2,Ben Parr,Co-Founder & CMO,Octane AI,https://www.youtube.com/watch?v=riKER3eQixs,3
3,Bernd Greifeneder,Chief Technology Officer & Founder,Dynatrace,https://www.youtube.com/watch?v=6bBI-WZYvTo,3
4,Bill Largent,CEO,Veeam,https://www.youtube.com/watch?v=OdrhPIBgZoE,3
5,Boris Renski,Co Founder and CMO,Mirantis,https://www.youtube.com/watch?v=EcxoQizrOPw,3
6,Brandon Nott,Senior Vice President of Product,UiPath,https://www.youtube.com/watch?v=SJFpjG_J6W0,3
7,Brett Hannath,Corporate Vice President & CMO,Intel,https://www.youtube.com/watch?v=sAPATcXqel0,3
8,Calline Sanchez,Vice President,IBM Worldwide Systems Lab Services,https://www.youtube.com/watch?v=DEHUqmEwFeg,3
9,Carol Carpenter,Senior Vice President and Chief Marketing Officer,VMware,https://www.youtube.com/watch?v=5KcRXgaimYU,3
10,Jaspreet Singh,CEO,Druva,https://www.youtube.com/watch?v=cf1vPcFW5to,3
11,Jean English,Senior Vice President and Chief Marketing Officer,NetApp,https://www.youtube.com/watch?v=ualozF4rCog,3
12,John Bara,CMO & President,Mintigo,https://www.youtube.com/watch?v=bTSFqIFJqrs,3
13,Karin Toubba,CEO,Kenna Security,https://www.youtube.com/watch?v=8NBAkJMA0sM,3
14,Michael Nicosia,Co-Founder & COO,Salt Security,https://www.youtube.com/watch?v=g3LhSzFiz1c,3
15,Mick Hollison,Founder & CEO,Redline Advisors,https://www.youtube.com/watch?v=uHlrQWbdP7A,3
16,Partha Seetala,Co-founder and CTO,Robin.io,https://www.youtube.com/watch?v=s7VaHEspI7E,3
17,Samantha Choi Cadley,CEO,Manual Labor Studio,https://www.youtube.com/watch?v=Q0_2N5hcBKo,3
18,Sarbjeet Johal,Founder & CEO,Stackpane,https://www.youtube.com/watch?v=zF9IycsTdsA,3
19,Scott Hebner,Vice President & CMO,IBM Data & AI,https://www.youtube.com/watch?v=AQw62zAq7Lw,3
20,Shlomo Kramer,Co-Founder & CEO,Cato Networks,https://www.youtube.com/watch?v=3_Y-QFr_U7k,3
21,Stefan Willkommer,CEO,TechDivision,https://www.youtube.com/watch?v=FerBo8ZdOsU,3
22,Tommy McClung,Co-Founder & CEO,Releasehub,https://www.youtube.com/watch?v=CQEM0li5rmQ,3
23,Abby Strong,CMO,Cribl,https://www.youtube.com/watch?v=1ei82jxf1kw,2
24,Alicia Tillman,CMO,SAP,https://www.youtube.com/watch?v=B3ZB0ymbXMk,2
25,Alison Biggan,CMO,Boomi,https://www.youtube.com/watch?v=78lxbm6VhYQ,2
26,Alison Wagonfeld,CMO,Google Cloud,https://www.youtube.com/watch?v=oNQm0gD5D7o,2
27,Allison Dew,CMO,Dell Technologies,https://www.youtube.com/watch?v=bAEmtntOaRs,2
28,Andreas Urschitz,CMO,Infineon,https://www.youtube.com/watch?v=QUgwtmPtN8A,2
29,Anna Griffin,CMO,Smartsheet,https://www.youtube.com/watch?v=LaZU2X5R6_E,2
30,Annie Weckesser,CMO,Uniphore,https://www.youtube.com/watch?v=RiobNN-i2dU,2
31,Anubhav Saxena,CMO,HCL,https://www.youtube.com/watch?v=FNNStsNemyg,2
32,Ben Gibson,CMO,Nutanix,https://www.youtube.com/watch?v=VGbo_2I08Ko,2
33,Beth Comstock,CMO,GE,https://www.youtube.com/watch?v=JCSQeVImbKQ,2
34,Beth Davidson,CMO,Agero,https://www.youtube.com/watch?v=Qtb-UFbSbms,2
35,Beth White,CMO,ServiceNow,https://www.youtube.com/watch?v=359buNsYgO4,2
36,Bobby Patrick,CMO,UiPath,https://www.youtube.com/watch?v=9zS7q_z5K-Q,2
37,Bobby Patrick,CMO,HPE Cloud,https://www.youtube.com/watch?v=RULJUGmz44k,2
38,Brian Goldfarb,CMO,Splunk,https://www.youtube.com/watch?v=xVrJe4ncRQw,2
39,Brian Reagan,CMO,Actifio,https://www.youtube.com/watch?v=SrEsTKDmgp0,2
40,Bruno Aziza,CMO,Alpine Data Labs,https://www.youtube.com/watch?v=QGK1smZGEkQ,2
41,Caroline Japic,CMO,Kenna Security,https://www.youtube.com/watch?v=8NBAkJMA0sM,2
42,Carrie Palin,CMO,Splunk,https://www.youtube.com/watch?v=byYQYnypDsc,2
43,Chandar Pattabhiram,CMO,Coupa,https://www.youtube.com/watch?v=yM2cpUc1vgY,2
44,Chandra Rangan,CMO,Neo4j,https://www.youtube.com/watch?v=fb-C_ZOANCs,2
45,Chris Port,COO,Boomi,https://www.youtube.com/watch?v=Nilshpvyvy4,2
46,Chris Powell,CMO,Commvault,https://www.youtube.com/watch?v=h1GPsSVcCMs,2
47,Dan Rogers,CMO,ServiceNow,https://www.youtube.com/watch?v=L0y_LZ3TaAU,2
48,Danny Allan,CTO,Veeam,https://www.youtube.com/watch?v=oqtF2KgkUMw,2
49,David Gee,CMO,Zuora,https://www.youtube.com/watch?v=tx1L51WXrc0,2
50,David Gibson,CMO,Varonis,https://www.youtube.com/watch?v=DZ9aWxLSm5w,2

## 8. Add Company Domains (Manual Verification)

Company domains were manually verified by visiting each company’s official website and entering the correct email domain.  
This ensures higher accuracy than automated guessing.

In [23]:
# Create empty domain column for manual filling
top50["domain"] = ""

# Export for manual domain enrichment
top50.to_csv("top50_with_domains.csv", index=False)

In [26]:
# Reload CSV after domains have been manually added
top50 = pd.read_excel("top50_with_domains.xlsx")
top50.head()

,Name,Title,Company,Youtube URL,rank,first,last,domain
0,Abhay Parasnis,Founder & CEO,Typeface,https://www.youtube.com/watch?v=U1jdmFW7-f4,3,abhay,parasnis,typeface.ai
1,Ben Parr,Co-Founder & CMO,Octane AI,https://www.youtube.com/watch?v=riKER3eQixs,3,ben,parr,octaneai.com
2,Bernd Greifeneder,Chief Technology Officer & Founder,Dynatrace,https://www.youtube.com/watch?v=6bBI-WZYvTo,3,bernd,greifeneder,dynatrace.com
3,Bill Largent,CEO,Veeam,https://www.youtube.com/watch?v=OdrhPIBgZoE,3,bill,largent,veeam.com
4,Boris Renski,Co Founder and CMO,Mirantis,https://www.youtube.com/watch?v=EcxoQizrOPw,3,boris,renski,mirantis.com

## 8. Generate Email Addresses

In [27]:
top50["first"] = top50["Name"].str.split().str[0].str.lower()
top50["last"] = top50["Name"].str.split().str[-1].str.lower()

In [28]:
top50["email1"] = top50["first"] + "." + top50["last"] + "@" + top50["domain"]
top50["email2"] = top50["first"].str[0] + top50["last"] + "@" + top50["domain"]
top50 = top50.drop(columns=["first","last","rank"])
top50.index=top50.index+1
top50["Company"] = top50["Company"].str.title()
top50

,Name,Title,Company,Youtube URL,domain,email1,email2
1,Abhay Parasnis,Founder & CEO,Typeface,https://www.youtube.com/watch?v=U1jdmFW7-f4,typeface.ai,abhay.parasnis@typeface.ai,aparasnis@typeface.ai
2,Ben Parr,Co-Founder & CMO,Octane Ai,https://www.youtube.com/watch?v=riKER3eQixs,octaneai.com,ben.parr@octaneai.com,bparr@octaneai.com
3,Bernd Greifeneder,Chief Technology Officer & Founder,Dynatrace,https://www.youtube.com/watch?v=6bBI-WZYvTo,dynatrace.com,bernd.greifeneder@dynatrace.com,bgreifeneder@dynatrace.com
4,Bill Largent,CEO,Veeam,https://www.youtube.com/watch?v=OdrhPIBgZoE,veeam.com,bill.largent@veeam.com,blargent@veeam.com
5,Boris Renski,Co Founder and CMO,Mirantis,https://www.youtube.com/watch?v=EcxoQizrOPw,mirantis.com,boris.renski@mirantis.com,brenski@mirantis.com
6,Brandon Nott,Senior Vice President of Product,Uipath,https://www.youtube.com/watch?v=SJFpjG_J6W0,uipath.com,brandon.nott@uipath.com,bnott@uipath.com
7,Brett Hannath,Corporate Vice President & CMO,Intel,https://www.youtube.com/watch?v=sAPATcXqel0,intel.com,brett.hannath@intel.com,bhannath@intel.com
8,Calline Sanchez,Vice President,Ibm Worldwide Systems Lab Services,https://www.youtube.com/watch?v=DEHUqmEwFeg,ibm.com,calline.sanchez@ibm.com,csanchez@ibm.com
9,Carol Carpenter,Senior Vice President and Chief Marketing Officer,Vmware,https://www.youtube.com/watch?v=5KcRXgaimYU,vmware.com,carol.carpenter@vmware.com,ccarpenter@vmware.com
10,Jaspreet Singh,CEO,Druva,https://www.youtube.com/watch?v=cf1vPcFW5to,druva.com,jaspreet.singh@druva.com,jsingh@druva.com
11,Jean English,Senior Vice President and Chief Marketing Officer,Netapp,https://www.youtube.com/watch?v=ualozF4rCog,netapp.com,jean.english@netapp.com,jenglish@netapp.com
12,John Bara,CMO & President,Mintigo,https://www.youtube.com/watch?v=bTSFqIFJqrs,mintigo.com,john.bara@mintigo.com,jbara@mintigo.com
13,Karin Toubba,CEO,Kenna Security,https://www.youtube.com/watch?v=8NBAkJMA0sM,kennasecurity.com,karin.toubba@kennasecurity.com,ktoubba@kennasecurity.com
14,Michael Nicosia,Co-Founder & COO,Salt Security,https://www.youtube.com/watch?v=g3LhSzFiz1c,salt.security,michael.nicosia@salt.security,mnicosia@salt.security
15,Mick Hollison,Founder & CEO,Redline Advisors,https://www.youtube.com/watch?v=uHlrQWbdP7A,redlineadvisors.com,mick.hollison@redlineadvisors.com,mhollison@redlineadvisors.com
16,Partha Seetala,Co-founder and CTO,Robin.Io,https://www.youtube.com/watch?v=s7VaHEspI7E,robin.io,partha.seetala@robin.io,pseetala@robin.io
17,Samantha Choi Cadley,CEO,Manual Labor Studio,https://www.youtube.com/watch?v=Q0_2N5hcBKo,manuallabor.studio,samantha.cadley@manuallabor.studio,scadley@manuallabor.studio
18,Sarbjeet Johal,Founder & CEO,Stackpane,https://www.youtube.com/watch?v=zF9IycsTdsA,stackpane.com,sarbjeet.johal@stackpane.com,sjohal@stackpane.com
19,Scott Hebner,Vice President & CMO,Ibm Data & Ai,https://www.youtube.com/watch?v=AQw62zAq7Lw,ibm.com,scott.hebner@ibm.com,shebner@ibm.com
20,Shlomo Kramer,Co-Founder & CEO,Cato Networks,https://www.youtube.com/watch?v=3_Y-QFr_U7k,catonetworks.com,shlomo.kramer@catonetworks.com,skramer@catonetworks.com
21,Stefan Willkommer,CEO,Techdivision,https://www.youtube.com/watch?v=FerBo8ZdOsU,techdivision.com,stefan.willkommer@techdivision.com,swillkommer@techdivision.com
22,Tommy McClung,Co-Founder & CEO,Releasehub,https://www.youtube.com/watch?v=CQEM0li5rmQ,releasehub.com,tommy.mcclung@releasehub.com,tmcclung@releasehub.com
23,Abby Strong,CMO,Cribl,https://www.youtube.com/watch?v=1ei82jxf1kw,cribl.io,abby.strong@cribl.io,astrong@cribl.io
24,Alicia Tillman,CMO,Sap,https://www.youtube.com/watch?v=B3ZB0ymbXMk,sap.com,alicia.tillman@sap.com,atillman@sap.com
25,Alison Biggan,CMO,Boomi,https://www.youtube.com/watch?v=78lxbm6VhYQ,boomi.com,alison.biggan@boomi.com,abiggan@boomi.com
26,Alison Wagonfeld,CMO,Google Cloud,https://www.youtube.com/watch?v=oNQm0gD5D7o,google.com,alison.wagonfeld@google.com,awagonfeld@google.com
27,Allison Dew,CMO,Dell Technologies,https://www.youtube.com/watch?v=bAEmtntOaRs,dell.com,allison.dew@dell.com,adew@dell.com
28,Andreas Urschitz,CMO,Infineon,https://www.youtube.com/watch?v=QUgwtmPtN8A,infineon.com,andreas.urschitz@infineon.com,aurschitz@infineon.com
29,Anna Griffin,CMO,Smartsheet,https://www.youtube.com/watch?v=LaZU2X5R6_E,smartsheet.com,anna.griffin@smartsheet.com,agriffin@smartsheet.com
30,Annie Weckesser,CMO,Uniphore,https://www.youtube.com/watch?v=RiobNN-i2dU,uniphore.com,annie.weckesser@uniphore.com,aweckesser@uniphore.com
31,Anubhav Saxena,CMO,Hcl,https://www.youtube.com/watch?v=FNNStsNemyg,hcltech.com,anubhav.saxena@hcltech.com,asaxena@hcltech.com
32,Ben Gibson,CMO,Nutanix,https://www.youtube.com/watch?v=VGbo_2I08Ko,nutanix.com,ben.gibson@nutanix.com,bgibson@nutanix.com
33,Beth Comstock,CMO,Ge,https://www.youtube.com/watch?v=JCSQeVImbKQ,ge.com,beth.comstock@ge.com,bcomstock@ge.com
34,Beth Davidson,CMO,Agero,https://www.youtube.com/watch?v=Qtb-UFbSbms,agero.com,beth.davidson@agero.com,bdavidson@agero.com
35,Beth White,CMO,Servicenow,https://www.youtube.com/watch?v=359buNsYgO4,servicenow.com,beth.white@servicenow.com,bwhite@servicenow.com
36,Bobby Patrick,CMO,Uipath,https://www.youtube.com/watch?v=9zS7q_z5K-Q,uipath.com,bobby.patrick@uipath.com,bpatrick@uipath.com
37,Bobby Patrick,CMO,Hpe Cloud,https://www.youtube.com/watch?v=RULJUGmz44k,hpe.com,bobby.patrick@hpe.com,bpatrick@hpe.com
38,Brian Goldfarb,CMO,Splunk,https://www.youtube.com/watch?v=xVrJe4ncRQw,splunk.com,brian.goldfarb@splunk.com,bgoldfarb@splunk.com
39,Brian Reagan,CMO,Actifio,https://www.youtube.com/watch?v=SrEsTKDmgp0,actifio.com,brian.reagan@actifio.com,breagan@actifio.com
40,Bruno Aziza,CMO,Alpine Data Labs,https://www.youtube.com/watch?v=QGK1smZGEkQ,alpinedatalabs.com,bruno.aziza@alpinedatalabs.com,baziza@alpinedatalabs.com
41,Caroline Japic,CMO,Kenna Security,https://www.youtube.com/watch?v=8NBAkJMA0sM,kennasecurity.com,caroline.japic@kennasecurity.com,cjapic@kennasecurity.com
42,Carrie Palin,CMO,Splunk,https://www.youtube.com/watch?v=byYQYnypDsc,splunk.com,carrie.palin@splunk.com,cpalin@splunk.com
43,Chandar Pattabhiram,CMO,Coupa,https://www.youtube.com/watch?v=yM2cpUc1vgY,coupa.com,chandar.pattabhiram@coupa.com,cpattabhiram@coupa.com
44,Chandra Rangan,CMO,Neo4J,https://www.youtube.com/watch?v=fb-C_ZOANCs,neo4j.com,chandra.rangan@neo4j.com,crangan@neo4j.com
45,Chris Port,COO,Boomi,https://www.youtube.com/watch?v=Nilshpvyvy4,boomi.com,chris.port@boomi.com,cport@boomi.com
46,Chris Powell,CMO,Commvault,https://www.youtube.com/watch?v=h1GPsSVcCMs,commvault.com,chris.powell@commvault.com,cpowell@commvault.com
47,Dan Rogers,CMO,Servicenow,https://www.youtube.com/watch?v=L0y_LZ3TaAU,servicenow.com,dan.rogers@servicenow.com,drogers@servicenow.com
48,Danny Allan,CTO,Veeam,https://www.youtube.com/watch?v=oqtF2KgkUMw,veeam.com,danny.allan@veeam.com,dallan@veeam.com
49,David Gee,CMO,Zuora,https://www.youtube.com/watch?v=tx1L51WXrc0,zuora.com,david.gee@zuora.com,dgee@zuora.com
50,David Gibson,CMO,Varonis,https://www.youtube.com/watch?v=DZ9aWxLSm5w,varonis.com,david.gibson@varonis.com,dgibson@varonis.com

In [ ]:
top50.to_csv("final_exec_emails.csv", index=False)